### ISSUE TITLE
codepa/> app doesn't open a project on Mac osx

### ISSUE THREAD

**Issue by lburgalassi** [andrewbrg/codepad-chrome-app#1]
Dear all I'm trying to use codepa on High Sierra but I'm not able to open a project: I select a folder then I clik ok and nothing happens, I'm back on home folder and any project is loaded.

Cheers
Lorenzo

**Comment by andrewbrg** [comment]
Can you please try updating to the latest version and see if the issue persists.

**Comment by ugajin-nijagu** [comment]
Works OK on Sierra v10.12
