### ISSUE TITLE
Doesn't appear in the Google Disk

### ISSUE THREAD

**Issue by nnseva** [andrewbrg/codepad-chrome-app#2]
Hi,

The Google Drive plugin menu (New->More->Connect more apps) allows me to select and connect your application as a Drive plugin, but I don't see any reference to your application in the Google Drive menu and can't even disconnect your application from the Google Drive options back.

Also, I've installed the application as a Chrome plugin. I've noticed that this is a different (from previous) installation option, but the reference to the application is the same: https://chrome.google.com/webstore/detail/code-pad-ide/adaepfiocmagdimjecpifghcgfjlfmkh

I don't see any reference from your application to the Google Drive, it probably means, that the application doesn't use Google Drive in any manner.

It looks like you are confusing users of your application now. Please, either remove the reference to your application from the Google Drive plugin list or add the Google Drive support to the application.

**Comment by andrewbrg** [comment]
Agreed, will remove the reference

**Comment by andrewbrg** [comment]
Reference removed in 1.0.88
