### ISSUE TITLE
Hypertext

### ISSUE THREAD

**Issue by Judimax** [andrewbrg/codepad-chrome-app#21]
I need hypertext enabled here as with some of the other editors can you help me with this

**Comment by Lithl** [comment]
What do you mean "hypertext enabled"? Codepad supports HTML files if that's what you mean.

**Comment by coder0107git** [comment]
@Judimax Can this be closed?

**Comment by coder0107git** [comment]
Related: #26 #79.

**Comment by Judimax** [comment]
Yes

Michael Odumosu
Fullstack Software Developer

*Information*
Tel:929-353-8278
Linkedin: https://www.linkedin.com/in/michael-odumosu-a58367b1
Facebook: https://www.facebook.com/mchael.odumosu
Github: https://github.com/MichaelOdumosu57
