### ISSUE TITLE
Prevent default undefined_1.js from opening every time

### ISSUE THREAD

**Issue by chivesz** [andrewbrg/codepad-chrome-app#30]
Please? This is a great editor, but there is no reason for this to open EVERY time. I could understand first run, however closing it every time is getting old...

**Comment by newsametcalfe** [comment]
May let us set a default file type to open, I mainly use .sql

**Comment by coder0107git** [comment]
Duplicate of #15. @chivesz Please close this issue.

**Comment by coder0107git** [comment]
@chivesz  Thank you for closing this issue.
