### ISSUE TITLE
Where is 'RUN' to execute a job?

### ISSUE THREAD

**Issue by dave6h** [andrewbrg/codepad-chrome-app#6]
Hi I am a new PYTHON beginner. I am excited to use. I can't find 'RUN' to execute a small job.

**Comment by Zipper213** [comment]
I dont think it has it, sorry, but you might be able to get something that allows you to run it.

**Comment by Cellestelle** [comment]
pls i need to run. where is the command please

**Comment by andrewbrg** [comment]
sorry, this feature is unsupported

**Comment by yjg2here** [comment]
please add the "Run" feature

**Comment by coder0107git** [comment]
You could try to run your python code [here](https://www.tutorialspoint.com/execute_python_online.php).
