### ISSUE TITLE
The Punchcard is dead ---  Long live the Codepad.

### ISSUE THREAD

**Issue by eketahuna** [andrewbrg/codepad-chrome-app#87]
Could user preferences include an option for a selectable (or full) edit line width?
Don't ask why I thought of punchcards!

**Comment by coder0107git** [comment]
Could you please explain more? I don't understand what you mean.

**Comment by coder0107git** [comment]
@eketahuna Are you meaning font size, number of characters before wrapping the line, or space between the lines?

**Comment by eketahuna** [comment]
RE:  an option for a selectable (or full) edit line width?

Sorry to bother you, but I've stopped using your CodePad.
I'm currently using Caret Mod v.0.3.5 on my Acer Spin 713 for local coding
after the Google OS and Browser combo seemed to break the code editors I
tried using after the original Caret disappeared --- actually the old Caret
still worked on my unsupported chromebook,  but a cable problem killed it
---  Luckily hosted web sites provide safe editors in their Cpanels ---
before that I used my own javascript file manager and code editor until
they disallowed writing to hosted PHP.

**Comment by coder0107git** [comment]
By the original Caret do you mean [this](https://chrome.google.com/webstore/detail/caret/fljalecfjciodhpcledpamjachpmelml)? Now I usually just use [`vscode.dev`](https://vscode.dev/)(the official version of vscode online) unless I need a text editor quickly without wanting to wait for `vscode` to load.

**Comment by eketahuna** [comment]
Yes, I used it for many years until a Chrome OS upgrade broke it for me
somehow.
I wrote Blackberry apps as they used QNX, which had impressed me in a small
commercial project for a friend.
I'm long retired and only maintain a monthly extension of a Toronto real
estate report for my son.

**Comment by coder0107git** [comment]
Could this be closed now since it sounds like the original feature request isn't wanted anymore?

**Comment by eketahuna** [comment]
Yes, please close this, and I wish you all the best with any future
products you work on !!

**Comment by coder0107git** [comment]
Thanks! Unfortunately I don't have permission in this repo to close issues.  :)

**Comment by eketahuna** [comment]
I closed it  😎

**Comment by coder0107git** [comment]
Thanks!
