### ISSUE TITLE
i cant run any script

### ISSUE THREAD

**Issue by Aslanpel** [andrewbrg/codepad-chrome-app#88]
plz add a run button

**Comment by coder0107git** [comment]
What coding language are you using? (e.g. CoffeeScript, Typescript, Javascript, HTML, CSS, Python, PHP, Ruby, C, C++, C#, Java, Rust, Lua, Haxe, Dart)

**Comment by MrICe19** [comment]
> 

python idk how to run do u know how?

**Comment by coder0107git** [comment]
What operating system are you using? (Windows, Mac OS, Chrome OS, or a Linux based OS)

**Comment by coder0107git** [comment]
The instructions on how to run differ largely depending on what OS you are using. If you are using Windows, Mac OS, or anything Linux based you need to install the OS specific package. If you are using Chrome OS you can either run it online or install the Linux package inside the Linux container (turned on by going to `Settings`->`Advanced`->`Developers`->`Linux development environment` and click `Turn on`), which is a version of `Debian`.

**Comment by MrICe19** [comment]
> What operating system are you using? (Windows, Mac OS, Chrome OS, or a Linux based OS)

chrome os

**Comment by coder0107git** [comment]
I would suggest first trying the Linux beta option and if that doesn't work then try googling for "run Python online". You could also try something like [python-browser-editor.onrender.com](https://python-browser-editor.onrender.com/), [wasmeditor.com](https://wasmeditor.com/), [pythonfiddle.leaningtech.com](http://pythonfiddle.leaningtech.com/), [webvm.io](https://webvm.io/), or [repl.leaningtech.com](https://repl.leaningtech.com/) (I can't vouch that any of the linked ones will work).

**Comment by coder0107git** [comment]
@Aslanpel Can this be closed now?

**Comment by coder0107git** [comment]
@Aslanpel @MrICe19 Can this be closed?
